### ISSUE TITLE
Сделать подгрузку баллов раньше таблицы

### ISSUE THREAD

**Issue by AlexSolari** [vuniverdevTeam/projectVuniver#4]
Баллы грузятся после загрузки таблицы, и все это дело выглядит стремно.
Было бы хорошо это исправить

**Comment by mrrbodia** [comment]
тут нз, спробую щось зробити, проблема в тому, що дані таблиці - в самому html, а прогрузка балів і всього повішано на onload
Спитав в Морозова, в нашому випадку це виходить нетривіальна задача, залишаю на потім, спробую ближче до вівторка щось зробити

**Comment by mrrbodia** [comment]
не зроблено
