### ISSUE TITLE
Сохранять фильтры

### ISSUE THREAD

**Issue by AlexSolari** [vuniverdevTeam/projectVuniver#5]
Сохранять фильтры областей городов и т.д.

**Comment by mrrbodia** [comment]
Льоша, передивись об"єкт який ти мені відправляєш, я знову просидів - нічого не вийшло, 3-й предмет не зберігає. Але я раніше якось не додумався подивитись на запит, в запиті його немає
mark5=123&mark1=123&sub2=2&mark2=123&sub3=&mark3=124&sub4=&mark4=&reg=&city=&Univer=&Fac=&Spec=
"sub3=&"

**Comment by mrrbodia** [comment]
Потрібно протестувати, з моїми даними все працює
